sudo: false
language: ruby
script: bundle exec rspec spec

matrix:
  include:
  - rvm: 2.0.0
    env: RAILS_VERSION=3.2
  - rvm: 2.1.6
    env: RAILS_VERSION=3.2
  - rvm: 2.2.6
    env: RAILS_VERSION=3.2
  - rvm: 2.3.3
    env: RAILS_VERSION=3.2

  - rvm: 2.0.0
    env: RAILS_VERSION=4.0
  - rvm: 2.1.6
    env: RAILS_VERSION=4.0
  - rvm: 2.2.6
    env: RAILS_VERSION=4.0
  - rvm: 2.3.3
    env: RAILS_VERSION=4.0

  - rvm: 2.0.0
    env: RAILS_VERSION=4.1
  - rvm: 2.1.6
    env: RAILS_VERSION=4.1
  - rvm: 2.2.6
    env: RAILS_VERSION=4.1
  - rvm: 2.3.3
    env: RAILS_VERSION=4.1

  - rvm: 2.0.0
    env: RAILS_VERSION=4.2
  - rvm: 2.1.6
    env: RAILS_VERSION=4.2
  - rvm: 2.2.6
    env: RAILS_VERSION=4.2
  - rvm: 2.3.3
    env: RAILS_VERSION=4.2

  - rvm: 2.2.6
    env: RAILS_VERSION=5.0
  - rvm: 2.3.3
    env: RAILS_VERSION=5.0
  - rvm: 2.4.0
    env: RAILS_VERSION=5.0
